[package]
name = "raphael-cli"
version = "0.2.2"
edition = "2024"

[[bench]]
name = "bench_cli"
harness = false

[dependencies]
raphael-sim = { workspace = true, features = ["serde"] }
raphael-solver = { workspace = true, features = ["serde"] }
raphael-data = { workspace = true }
rayon = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"

clap = { version = "4.5.51", features = ["derive", "wrap_help", "env"] }

env_logger = "0.11.8"
