[package]
name = "raphael-data"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
raphael-sim = { workspace = true }
phf = "0.11.2"
serde = { version = "1.0.215", features = ["derive"], optional = true }

[features]
serde = ["dep:serde", "raphael-sim/serde"]
