[package]
name = "raphael-data"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
raphael-sim = { workspace = true }
serde = { version = "1.0.215", features = ["derive"], optional = true }

[dev-dependencies]
expect-test = "1.5.1"
criterion = "0.5.1"
rand = "0.9.1"

[features]
serde = ["dep:serde", "raphael-sim/serde"]

[[bench]]
name = "bench_game_data"
harness = false
