[alias]
tr = "test --package raphael-solver --test * -- -Z unstable-options --report-time"
rr = "run --release --package raphael-solver --example macro_solver_example"
ud = "run --package raphael-data-updater"
