[alias]
tr = "test --package raphael-solver --test *"
tr1 = "test --package raphael-solver --test * -- -Z unstable-options --report-time --test-threads=1"
rr = "run --release --package raphael-solver --example macro_solver_example"
ud = "run --package raphael-data-updater"
