name: Check commit

on:
  push:
    branches: ["preview", "main"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always
  RUST_STABLE_VERSION: 1.92.0
  RUST_NIGHTLY_VERSION: nightly-2026-05-10

jobs:
  check-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check that workspace builds with MSRV
        run: cargo +${{ env.RUST_STABLE_VERSION }} check --workspace

      - name: Install required components
        run: rustup component add --toolchain ${{ env.RUST_NIGHTLY_VERSION }} clippy rust-src
      - name: Check for clippy warnings when building native version
        run: cargo +${{ env.RUST_NIGHTLY_VERSION }} clippy --workspace -- -Dwarnings
      - name: Check for clippy warnings when building web version
        run: BASE_URL=localhost cargo +${{ env.RUST_NIGHTLY_VERSION }} clippy --config ./.cargo/config_wasm.toml -- -Dwarnings

  check-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check that workspace builds with MSRV
        run: cargo +${{ env.RUST_STABLE_VERSION }} check --workspace

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run all tests
        run: cargo test --verbose --workspace
