name: Publish Release Assets

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use nightly toolchain
        run: rustup update nightly && rustup default nightly
      - name: Build
        run: cargo build --release
      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ./target/release/raphael-xiv
          asset_name: raphael_x86_64_linux
          asset_content_type: application/octet-stream

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use nightly toolchain
        run: rustup update nightly && rustup default nightly
      - name: Build
        run: cargo build --release
      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ./target/release/raphael-xiv.exe
          asset_name: raphael_x86_64_windows.exe
          asset_content_type: application/octet-stream
          
